// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SteamTracker.Infrastructure.Persistence;

#nullable disable

namespace SteamTracker.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SteamTrackerDbContext))]
    partial class SteamTrackerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SteamTracker.Core.Entities.Alert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Channel")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal?>("DropPercentage")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastTriggeredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TargetPrice")
                        .HasColumnType("jsonb")
                        .HasColumnName("TargetPrice");

                    b.Property<Guid>("TrackedItemId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TrackedItemId");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("SteamTracker.Core.Entities.PriceSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MedianPrice")
                        .HasColumnType("jsonb")
                        .HasColumnName("MedianPrice");

                    b.Property<Guid>("TrackedItemId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Volume")
                        .HasColumnType("integer");

                    b.ComplexProperty<Dictionary<string, object>>("LowestPrice", "SteamTracker.Core.Entities.PriceSnapshot.LowestPrice#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("LowestPriceAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("LowestPriceCurrency");
                        });

                    b.HasKey("Id");

                    b.HasIndex("TrackedItemId", "CapturedAt");

                    b.ToTable("PriceSnapshots");
                });

            modelBuilder.Entity("SteamTracker.Core.Entities.TrackedItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AppId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("MarketHashName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AppId", "MarketHashName")
                        .IsUnique();

                    b.ToTable("TrackedItems");
                });

            modelBuilder.Entity("SteamTracker.Core.Entities.Alert", b =>
                {
                    b.HasOne("SteamTracker.Core.Entities.TrackedItem", "TrackedItem")
                        .WithMany("Alerts")
                        .HasForeignKey("TrackedItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrackedItem");
                });

            modelBuilder.Entity("SteamTracker.Core.Entities.PriceSnapshot", b =>
                {
                    b.HasOne("SteamTracker.Core.Entities.TrackedItem", "TrackedItem")
                        .WithMany("Snapshots")
                        .HasForeignKey("TrackedItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrackedItem");
                });

            modelBuilder.Entity("SteamTracker.Core.Entities.TrackedItem", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("Snapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
